# -*- coding: utf-8 -*-
"""desafio_ac1_master_sdwan.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DNQSXZE6xeYl6jCki6aIdCyPui_Y1hEW
"""

"""
Desafio de Fechamento da AC-1 - Motor de Decisioning SD-WAN Zero-Trust

RELATORIO TECNICO (gerado depois de rodar o script com seed 2026,
que e fixa, entao o resultado abaixo e sempre o mesmo)
-----------------------------------------------------------------
Cenario: 12 roteadores (0 a 11), origem fixa no no 0 e destino fixo
no no 11. Nem todo par de roteadores tem link fisico direto - a
topologia foi montada como uma arvore geradora aleatoria (garante
que todos os 12 nos estao alcancaveis) mais 14 enlaces extras,
excluindo de proposito um link direto entre 0 e 11 (assim o
algoritmo e realmente obrigado a escolher uma rota por nos
intermediarios, e nao so "pular direto").

Cada no recebeu um indice de reputacao de seguranca aleatorio entre
20 e 100. Os nos 3, 5 e 9 ficaram com reputacao abaixo de 50 (27.3,
40.3 e 25.0, respectivamente) e por isso sao tratados como nao
confiaveis. Os nos 0 e 11 ficam de fora dessa checagem porque sao os
roteadores da propria operadora (origem e destino fixos), entao sao
sempre considerados confiaveis por definicao.

Rota selecionada pelo algoritmo genetico: 0 -> 2 -> 11
  latencia total: 88.15 ms | perda de pacotes total: 10.35%
  penalidade de seguranca: 0 (nenhum no nao confiavel na rota)
  fitness final: 139.90

Justificativa do desvio em relacao aos nos penalizados:
a rota escolhida evita completamente os nos 3, 5 e 9. Pra confirmar
que essa e realmente a melhor decisao (e nao so o algoritmo "fugindo"
de qualquer jeito), comparamos com rotas reais alternativas que
passam por esses nos, usando os mesmos enlaces existentes na
topologia:

  0 -> 2 -> 5  -> 11  | latencia 117.25 ms | perda 11.21% | fitness 5173.30
  0 -> 9 -> 2  -> 11  | latencia  84.19 ms | perda 12.05% | fitness 5144.46
  0 -> 9 -> 3  -> 11  | latencia  87.60 ms | perda 10.75% | fitness 5141.33

O caso mais interessante e o segundo: a rota passando pelo no 9 tem
ATE MENOS latencia (84.19 ms) do que a rota escolhida (88.15 ms).
Ou seja, olhando so pra latencia e perda de pacotes, essa rota seria
"melhor". Mas como o no 9 tem reputacao 25.0 (< 50), ela recebe a
penalidade de seguranca de 5000, o que faz o fitness dela disparar
pra mais de 5100. E exatamente esse o papel da penalidade: garantir
que uma rota mais rapida, mas insegura, nunca seja escolhida no
lugar de uma rota confiavel, mesmo quando a diferenca de desempenho
de rede e pequena.

Pesos usados na funcao de fitness: w1 = 1.0 (latencia) e
w2 = 5.0 (perda de pacotes). Damos mais peso a perda de pacotes
porque, num cenario SD-WAN Zero-Trust, confiabilidade da entrega
importa mais do que alguns milissegundos de atraso.
-----------------------------------------------------------------
"""

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import time

np.random.seed(2026)

NUM_NOS = 12
ORIGEM = 0
DESTINO = 11

# ============================================================
# 1. TOPOLOGIA - MATRIZ DE ADJACENCIA
# ============================================================
# Arvore geradora aleatoria garante que todo mundo esta conectado.
ordem = np.random.permutation(NUM_NOS)
conectados = [ordem[0]]
arestas = set()
for no in ordem[1:]:
    alvo = np.random.choice(conectados)
    arestas.add((min(no, alvo), max(no, alvo)))
    conectados.append(no)

# Enlaces extras pra dar mais opcoes de rota (a arvore sozinha so
# tem 1 caminho por par de nos). De proposito, nao deixamos um link
# direto entre origem e destino - assim o algoritmo precisa mesmo
# escolher nos intermediarios.
pares_possiveis = [
    (i, j) for i in range(NUM_NOS) for j in range(i + 1, NUM_NOS)
    if (i, j) not in arestas and (i, j) != (ORIGEM, DESTINO)
]
np.random.shuffle(pares_possiveis)
arestas.update(pares_possiveis[:14])
arestas.discard((ORIGEM, DESTINO))

adjacencia = np.zeros((NUM_NOS, NUM_NOS), dtype=int)
for i, j in arestas:
    adjacencia[i, j] = 1
    adjacencia[j, i] = 1

# ============================================================
# 2. REPUTACAO DE SEGURANCA DOS NOS
# ============================================================
reputacao = np.random.uniform(20, 100, NUM_NOS)

# origem e destino sao roteadores da propria rede, entao ficam de
# fora da checagem de confianca (sempre sao considerados confiaveis)
NOS_NAO_CONFIAVEIS = set(
    i for i in range(NUM_NOS)
    if reputacao[i] < 50 and i not in (ORIGEM, DESTINO)
)

# ============================================================
# 3. ATRIBUTOS DOS ENLACES (LATENCIA E PERDA DE PACOTES)
# ============================================================
# Pares sem link direto recebem um valor "sentinela" bem alto, pra
# funcionar como uma penalizacao natural (o mesmo espirito da
# penalidade de SLA do Exercicio 2): se o enlace nao existe de
# verdade, usa-lo custa muito caro.
SENTINELA_LATENCIA = 500.0
SENTINELA_PERDA = 80.0

latencia = np.full((NUM_NOS, NUM_NOS), SENTINELA_LATENCIA)
perda = np.full((NUM_NOS, NUM_NOS), SENTINELA_PERDA)
np.fill_diagonal(latencia, 0.0)
np.fill_diagonal(perda, 0.0)

for i, j in arestas:
    lat = np.random.uniform(5, 60)
    perc = np.random.uniform(0, 15)
    latencia[i, j] = latencia[j, i] = lat
    perda[i, j] = perda[j, i] = perc

# ============================================================
# 4. FUNCAO DE FITNESS
# ============================================================
W1 = 1.0          # peso da latencia
W2 = 5.0          # peso da perda de pacotes
P_SEGURANCA = 5000.0

NOS_INTERMEDIARIOS = [n for n in range(NUM_NOS) if n not in (ORIGEM, DESTINO)]
K_MIN, K_MAX = 1, len(NOS_INTERMEDIARIOS)


def montar_rota(perm, k):
    """
    O individuo e composto por uma permutacao dos nos intermediarios
    mais um "corte" k: so os k primeiros nos da permutacao entram de
    fato na rota. Isso permite que o algoritmo evolua rotas de
    tamanhos diferentes, e nao so rotas que passam por todo mundo.
    """
    return [ORIGEM] + [int(n) for n in perm[:k]] + [DESTINO]


def calcular_fitness(perm, k):
    rota = montar_rota(perm, k)

    latencia_total = 0.0
    perda_total = 0.0
    for i in range(len(rota) - 1):
        latencia_total += latencia[rota[i], rota[i + 1]]
        perda_total += perda[rota[i], rota[i + 1]]

    penalidade_seguranca = (
        P_SEGURANCA
        if any(no in NOS_NAO_CONFIAVEIS for no in rota[1:-1])
        else 0.0
    )

    fitness = W1 * latencia_total + W2 * perda_total + penalidade_seguranca

    return fitness, latencia_total, perda_total, penalidade_seguranca, rota


# ============================================================
# 5. OPERADORES GENETICOS
# ============================================================
def crossover_ox(pai1, pai2):
    tamanho = len(pai1)
    filho = np.full(tamanho, -1, dtype=int)

    p1, p2 = sorted(np.random.choice(tamanho, 2, replace=False))
    filho[p1:p2] = pai1[p1:p2]

    posicao = p2
    for elemento in pai2:
        if elemento not in filho:
            if posicao >= tamanho:
                posicao = 0
            filho[posicao] = elemento
            posicao += 1

    return filho


def mutacao_swap(perm, taxa):
    perm = perm.copy()
    if np.random.rand() < taxa:
        i1, i2 = np.random.choice(len(perm), 2, replace=False)
        perm[i1], perm[i2] = perm[i2], perm[i1]
    return perm


def selecao_torneio(pop_perm, pop_k, fitness_vals, tamanho=3):
    participantes = np.random.choice(len(pop_perm), tamanho, replace=False)
    melhor = participantes[np.argmin([fitness_vals[i] for i in participantes])]
    return pop_perm[melhor], pop_k[melhor]


# ============================================================
# 6. EXECUCAO DO ALGORITMO GENETICO
# ============================================================
TAM_POP = 20
GERACOES = 150
TAXA_MUT_ORDEM = 0.3
TAXA_MUT_K = 0.2

pop_perm = [np.random.permutation(NOS_INTERMEDIARIOS) for _ in range(TAM_POP)]
pop_k = [np.random.randint(K_MIN, K_MAX + 1) for _ in range(TAM_POP)]

melhor_fitness_global = np.inf
melhor_perm_global = None
melhor_k_global = None
historico_melhor = []

tempo_inicio = time.time()

for geracao in range(GERACOES):
    resultados = [calcular_fitness(pop_perm[i], pop_k[i]) for i in range(TAM_POP)]
    fitness_populacao = [r[0] for r in resultados]

    idx_melhor = np.argmin(fitness_populacao)
    if fitness_populacao[idx_melhor] < melhor_fitness_global:
        melhor_fitness_global = fitness_populacao[idx_melhor]
        melhor_perm_global = pop_perm[idx_melhor].copy()
        melhor_k_global = pop_k[idx_melhor]

    historico_melhor.append(melhor_fitness_global)

    # elitismo
    novos_perm = [melhor_perm_global.copy()]
    novos_k = [melhor_k_global]

    while len(novos_perm) < TAM_POP:
        pai1_perm, pai1_k = selecao_torneio(pop_perm, pop_k, fitness_populacao)
        pai2_perm, pai2_k = selecao_torneio(pop_perm, pop_k, fitness_populacao)

        filho_perm = crossover_ox(pai1_perm, pai2_perm)
        filho_perm = mutacao_swap(filho_perm, TAXA_MUT_ORDEM)

        filho_k = pai1_k if np.random.rand() < 0.5 else pai2_k
        if np.random.rand() < TAXA_MUT_K:
            filho_k = int(np.clip(filho_k + np.random.choice([-1, 1]), K_MIN, K_MAX))

        novos_perm.append(filho_perm)
        novos_k.append(filho_k)

    pop_perm, pop_k = novos_perm, novos_k

tempo_execucao = (time.time() - tempo_inicio) * 1000

# ============================================================
# 7. RESULTADOS
# ============================================================
fitness_final, lat_final, perda_final, penal_final, rota_final = calcular_fitness(
    melhor_perm_global, melhor_k_global
)

print("=" * 60)
print("DESAFIO AC-1 - Motor de Decisioning SD-WAN Zero-Trust")
print("=" * 60)
print(f"Nos nao confiaveis na topologia (reputacao < 50): {sorted(NOS_NAO_CONFIAVEIS)}")
print(f"Rota selecionada: {rota_final}")
print(f"Latencia total: {lat_final:.2f} ms")
print(f"Perda de pacotes total: {perda_final:.2f}%")
print(f"Penalidade de seguranca: {penal_final:.0f}")
print(f"Fitness final: {fitness_final:.2f}")
print(f"Tempo de execucao: {tempo_execucao:.2f} ms")
print("=" * 60)

# comparacao com rotas reais que passam por nos nao confiaveis,
# pra mostrar por que o algoritmo evitou essas alternativas
print("\nComparacao com rotas alternativas (usando enlaces reais):")
alternativas = [[0, 2, 5, 11], [0, 9, 2, 11], [0, 9, 3, 11]]
for alt in alternativas:
    f, l, p, pen = (lambda r: (
        sum(latencia[r[i], r[i+1]] for i in range(len(r)-1)) * W1
        + sum(perda[r[i], r[i+1]] for i in range(len(r)-1)) * W2
        + (P_SEGURANCA if any(n in NOS_NAO_CONFIAVEIS for n in r[1:-1]) else 0),
        sum(latencia[r[i], r[i+1]] for i in range(len(r)-1)),
        sum(perda[r[i], r[i+1]] for i in range(len(r)-1)),
        P_SEGURANCA if any(n in NOS_NAO_CONFIAVEIS for n in r[1:-1]) else 0
    ))(alt)
    print(f"  {alt} -> fitness {f:.2f} (latencia {l:.2f} ms, perda {p:.2f}%, penalidade {pen:.0f})")

plt.figure(figsize=(9, 5))
plt.plot(historico_melhor)
plt.title("Convergencia - Roteamento SD-WAN Zero-Trust")
plt.xlabel("Geracao")
plt.ylabel("Fitness (quanto menor, melhor)")
plt.grid(True)
plt.savefig("convergencia_desafio_ac1.png", dpi=150, bbox_inches="tight")
print("\nGrafico salvo em convergencia_desafio_ac1.png")