# -*- coding: utf-8 -*-
"""exercicio02_aula04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DNQSXZE6xeYl6jCki6aIdCyPui_Y1hEW
"""

"""
Exercicio 2 - Insercao de Penalidades por Descumprimento de SLA
CIAO - Aula 04 - AC-1 Parte Final

Objetivo do roteiro: calcular uma penalidade estatica de +1000 ms
para cada enlace da rota cuja latencia passe do limite de SLA
(50 ms). A logica em si ja estava pronta no roteiro; a unica coisa
que a gente ajustou foi imprimir tambem QUAIS enlaces estouraram o
limite, pra ficar mais facil de conferir o resultado (sem isso, o
numero final de custo nao mostra o motivo da penalidade).
"""

import numpy as np

np.random.seed(15)
matriz_latencia = np.random.uniform(5, 80, (6, 6))


def calcular_custo_com_sla(rota, matriz, limite_sla=50.0):
    custo_total = 0.0
    penalidade = 0.0
    enlaces_violados = []

    for i in range(len(rota) - 1):
        origem = rota[i]
        destino = rota[i + 1]
        latencia_enlace = matriz[origem, destino]
        custo_total += latencia_enlace

        # Incrementa a penalidade caso a latencia do enlace ultrapasse o SLA
        if latencia_enlace > limite_sla:
            penalidade += 1000.0
            enlaces_violados.append((origem, destino, latencia_enlace))

    return custo_total + penalidade, custo_total, penalidade, enlaces_violados


rota_teste = np.array([0, 1, 2, 3, 4, 5])
custo_final, custo_sem_penalidade, penalidade_total, violacoes = calcular_custo_com_sla(rota_teste, matriz_latencia)

print("=" * 60)
print("EXERCICIO 2 - Penalidade de SLA")
print("=" * 60)
print(f"Rota testada: {rota_teste}")
print(f"Custo somando so as latencias: {custo_sem_penalidade:.2f} ms")
print(f"Penalidade total aplicada: {penalidade_total:.2f} ms")

if violacoes:
    print(f"Enlaces que passaram do limite de {50.0} ms:")
    for origem, destino, latencia in violacoes:
        print(f"  {origem} -> {destino}: {latencia:.2f} ms")
else:
    print("Nenhum enlace passou do limite de SLA.")

print(f"[Exercicio 2] Custo Total (Com Penalizacoes de SLA): {custo_final:.2f} ms")
print("=" * 60)