# -*- coding: utf-8 -*-
"""exercicio01_aula04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DNQSXZE6xeYl6jCki6aIdCyPui_Y1hEW
"""

"""
Exercicio 1 - Analise do Elitismo na Estabilidade Algoritmica
CIAO - Aula 04 - AC-1 Parte Final

O roteiro pede pra alterar a flag USAR_ELITISMO e observar o efeito
na curva de convergencia. Em vez de rodar o algoritmo duas vezes "na
mao" (mudando a flag e rodando de novo), colocamos o algoritmo dentro
de uma funcao e chamamos ela duas vezes, com e sem elitismo, usando a
MESMA seed nas duas execucoes. Assim a populacao inicial e a matriz
de distancias sao identicas nos dois casos, e a unica coisa que muda
de fato e o elitismo. Isso deixa a comparacao mais justa.

Outra coisa que mudamos em relacao ao roteiro original: alem do
"melhor fitness ja visto" (que so pode melhorar, por definicao),
guardamos tambem o "melhor fitness DA GERACAO", que pode piorar de
uma geracao pra outra se o individuo campeao se perder no processo.
E exatamente essa piora que o elitismo evita, entao esse e o numero
que mostra a diferenca entre as duas execucoes.
"""

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


def calcular_custo(rota, matriz):
    dist = 0
    for i in range(len(rota) - 1):
        dist += matriz[rota[i], rota[i + 1]]
    return dist + matriz[rota[-1], rota[0]]


NUM_NOS = 8
TAM_POP = 40
GERACOES = 80
TAXA_MUTACAO = 0.3
SEED = 42


def rodar_ag(usar_elitismo):
    # mesma seed nas duas execucoes -> mesma populacao inicial e
    # mesma matriz de distancias. A unica diferenca e o elitismo.
    np.random.seed(SEED)

    matriz_teste = np.random.uniform(10, 100, (NUM_NOS, NUM_NOS))
    populacao = [np.random.permutation(NUM_NOS) for _ in range(TAM_POP)]

    melhor_da_geracao = []   # pode piorar sem elitismo
    melhor_ja_visto = []     # nunca piora (so serve de referencia)
    media_da_geracao = []

    recorde = np.inf

    for g in range(GERACOES):
        custos = [calcular_custo(ind, matriz_teste) for ind in populacao]

        melhor_idx = np.argmin(custos)
        melhor_da_geracao.append(custos[melhor_idx])
        media_da_geracao.append(np.mean(custos))

        if custos[melhor_idx] < recorde:
            recorde = custos[melhor_idx]
        melhor_ja_visto.append(recorde)

        novos = []
        if usar_elitismo:
            novos.append(populacao[melhor_idx].copy())

        while len(novos) < TAM_POP:
            i1, i2 = np.random.choice(TAM_POP, 2, replace=False)
            pai = populacao[i1] if custos[i1] < custos[i2] else populacao[i2]

            filho = pai.copy()
            if np.random.rand() < TAXA_MUTACAO:
                idx1, idx2 = np.random.choice(NUM_NOS, 2, replace=False)
                filho[idx1], filho[idx2] = filho[idx2], filho[idx1]
            novos.append(filho)

        populacao = novos

    return melhor_da_geracao, melhor_ja_visto, media_da_geracao


hist_com, recorde_com, media_com = rodar_ag(True)
hist_sem, recorde_sem, media_sem = rodar_ag(False)

# quantas vezes o melhor DA GERACAO piorou em relacao a geracao anterior
pioras_com = sum(1 for i in range(1, len(hist_com)) if hist_com[i] > hist_com[i - 1])
pioras_sem = sum(1 for i in range(1, len(hist_sem)) if hist_sem[i] > hist_sem[i - 1])

print("=" * 60)
print("EXERCICIO 1 - Elitismo x Estabilidade")
print("=" * 60)
print(f"Custo do melhor individuo ao final (COM elitismo): {recorde_com[-1]:.2f}")
print(f"Custo do melhor individuo ao final (SEM elitismo): {recorde_sem[-1]:.2f}")
print(f"Quantas geracoes o 'melhor da geracao' piorou (COM elitismo): {pioras_com}")
print(f"Quantas geracoes o 'melhor da geracao' piorou (SEM elitismo): {pioras_sem}")
print("=" * 60)

plt.figure(figsize=(9, 5))
plt.plot(hist_com, label="Melhor da geracao - com elitismo")
plt.plot(hist_sem, label="Melhor da geracao - sem elitismo")
plt.title("Efeito do elitismo na curva de convergencia")
plt.xlabel("Geracao")
plt.ylabel("Custo (quanto menor, melhor)")
plt.grid(True)
plt.legend()
plt.savefig("convergencia_elitismo.png", dpi=150, bbox_inches="tight")
print("Grafico salvo em convergencia_elitismo.png")