# -*- coding: utf-8 -*-
"""exercicio03_aula04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DNQSXZE6xeYl6jCki6aIdCyPui_Y1hEW
"""

"""
Exercicio 3 - Balanceamento de Carga em Servidores
CIAO - Aula 04 - AC-1 Parte Final

Problema: temos 20 tarefas, cada uma com um tempo de processamento
fixo, e 4 servidores. Precisamos decidir em qual servidor cada
tarefa vai rodar, de forma a minimizar o MAKESPAN (o tempo do
servidor que fica mais sobrecarregado no final).

Representacao do individuo: um vetor de 20 posicoes, com valores
entre 0 e 3. A posicao do vetor e a tarefa, o valor guardado ali e
o servidor escolhido para aquela tarefa. Por exemplo:

    individuo = [0, 2, 1, 0, ...]
    tarefa 0 -> servidor 0
    tarefa 1 -> servidor 2
    tarefa 2 -> servidor 1
    ...

Esse problema NAO e uma permutacao (pode repetir servidor a vontade,
inclusive um servidor pode ficar sem nenhuma tarefa), entao o
crossover OX usado no exemplo do professor nao se aplica aqui. Por
isso usamos crossover uniforme (cada gene do filho vem de um dos
dois pais, sorteado gene a gene) e mutacao que troca o servidor de
uma tarefa por outro servidor aleatorio.
"""

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

np.random.seed(42)

TEMPOS = np.array([12, 35, 40, 8, 15, 22, 19, 45, 60, 31,
                    14, 28, 50, 18, 25, 33, 42, 10, 5, 29])

NUM_TAREFAS = len(TEMPOS)
NUM_SERVIDORES = 4

TAM_POP = 60
GERACOES = 150
TAXA_MUTACAO = 0.1  # probabilidade de mutar CADA gene (tarefa)


def calcular_makespan(individuo, tempos, num_servidores):
    carga = np.zeros(num_servidores)
    for tarefa, servidor in enumerate(individuo):
        carga[servidor] += tempos[tarefa]
    return carga.max(), carga


def criar_individuo():
    return np.random.randint(0, NUM_SERVIDORES, size=NUM_TAREFAS)


def selecao_torneio(populacao, fitness, tamanho=3):
    participantes = np.random.choice(len(populacao), tamanho, replace=False)
    melhor = participantes[np.argmin([fitness[i] for i in participantes])]
    return populacao[melhor]


def crossover_uniforme(pai1, pai2):
    mascara = np.random.randint(0, 2, size=NUM_TAREFAS)
    return np.where(mascara == 0, pai1, pai2)


def mutacao(individuo, taxa):
    individuo = individuo.copy()
    for i in range(len(individuo)):
        if np.random.rand() < taxa:
            individuo[i] = np.random.randint(0, NUM_SERVIDORES)
    return individuo


populacao = [criar_individuo() for _ in range(TAM_POP)]

historico_melhor = []
melhor_individuo_global = None
melhor_makespan_global = np.inf

for geracao in range(GERACOES):
    fitness = [calcular_makespan(ind, TEMPOS, NUM_SERVIDORES)[0] for ind in populacao]

    idx_melhor = np.argmin(fitness)
    if fitness[idx_melhor] < melhor_makespan_global:
        melhor_makespan_global = fitness[idx_melhor]
        melhor_individuo_global = populacao[idx_melhor].copy()

    historico_melhor.append(melhor_makespan_global)

    nova_populacao = [melhor_individuo_global.copy()]  # elitismo

    while len(nova_populacao) < TAM_POP:
        pai1 = selecao_torneio(populacao, fitness)
        pai2 = selecao_torneio(populacao, fitness)
        filho = crossover_uniforme(pai1, pai2)
        filho = mutacao(filho, TAXA_MUTACAO)
        nova_populacao.append(filho)

    populacao = nova_populacao

makespan_final, cargas_final = calcular_makespan(melhor_individuo_global, TEMPOS, NUM_SERVIDORES)

print("=" * 60)
print("Exercicio 3 - Balanceamento de Carga em Servidores")
print("=" * 60)
print(f"Alocacao encontrada (tarefa -> servidor): {melhor_individuo_global}")
for s in range(NUM_SERVIDORES):
    tarefas_do_servidor = [i for i, srv in enumerate(melhor_individuo_global) if srv == s]
    print(f"  Servidor {s}: tarefas {tarefas_do_servidor} | carga = {cargas_final[s]:.0f}s")
print(f"Makespan (maior carga entre os servidores): {makespan_final:.2f} s")
print(f"Soma de todos os tempos de tarefa: {TEMPOS.sum()} s")
print(f"Media teorica por servidor (limite inferior ideal): {TEMPOS.sum() / NUM_SERVIDORES:.2f} s")
print("=" * 60)

plt.figure(figsize=(8, 5))
plt.plot(historico_melhor)
plt.title("Convergencia - Balanceamento de Carga em Servidores")
plt.xlabel("Geracao")
plt.ylabel("Makespan (quanto menor, melhor)")
plt.grid(True)
plt.savefig("convergencia_exercicio03.png", dpi=150, bbox_inches="tight")
print("Grafico salvo em convergencia_exercicio03.png")